# Generated by Django 4.2.8 on 2023-12-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('completed', 'Completed'), ('create', 'Create')], default='create', max_length=20),
        ),
    ]
